default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_backend_development

test:
  <<: *default
  database: rails_backend_test

production:
  <<: *default
  database: rails_backend_production
  username: rails_backend
  password: <%= ENV["RAILS_BACKEND_DATABASE_PASSWORD"] %>
